### ISSUE TITLE
mobSocial installing problem

### ISSUE THREAD

**Issue by 102306071** [mobsoftware/mobSocial.nopCommercePlugin#2]
Following the steps of "How to in stall"

I encountered the error seems the navigation can't be showed properly.
I couldn't figure out how to fix it...

Note: My nopcommerce version is 3.70 
```

The view 'mobSocial/SocialNetworkNavigation/PublicInfo' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Themes/mobSocialDefault/Views/SocialNetworkNavigation/mobSocial/SocialNetworkNavigation/PublicInfo.cshtml
~/Themes/mobSocialDefault/Views/Shared/mobSocial/SocialNetworkNavigation/PublicInfo.cshtml
~/Views/SocialNetworkNavigation/mobSocial/SocialNetworkNavigation/PublicInfo.cshtml
~/Views/Shared/mobSocial/SocialNetworkNavigation/PublicInfo.cshtml
~/Administration/Views/SocialNetworkNavigation/mobSocial/SocialNetworkNavigation/PublicInfo.cshtml
~/Administration/Views/Shared/mobSocial/SocialNetworkNavigation/PublicInfo.cshtml
~/Plugins/MobSocial.Suite/Views/mobSocial/SocialNetworkNavigation/PublicInfo.cshtml
~/Plugins/MobSocial.Suite/Themes/MobSocialDefault/Views/SocialNetworkNavigation/mobSocial/SocialNetworkNavigation/PublicInfo.cshtml
```

**Comment by wittyansh** [comment]
Hi,
Can you please verify if the file PublicInfo.cshtml is present in `~/Plugins/Nop.Plugin.Widgets.mobSocial/Views/mobSocial/SocialNetworkNavigation`
or
`~/Plugins/MobSocial.Suite/Views/mobSocial/SocialNetworkNavigation`

**Comment by 102306071** [comment]
Hi,
Thank you for your answers.
My file PublicInfo.cshtml is present in
`~/Plugins/MobSocial/Views/mobSocial/SocialNetworkNavigation`

**Comment by wittyansh** [comment]
The name of your plugin's folder should be **MobSocial.Suite** 
~/Plugins/**MobSocial.Suite**/Views/mobSocial/SocialNetworkNavigation
It's required for proper functioning.

**Comment by 102306071** [comment]
Hi,
Thank you for the useful information. The error was solved after rename the folder name to "MobSocial.Suite ".
But I faced another strange problem that I clicked "My profile" page, and it could show the page properly for a while(about 1~2 second, depend on the loading speed). After the page was loaded completely, it redirected to a 404 error.
I was wondering if I need to do some setup in my administration area or I need to update either javascript files or the mobSocial theme.

The [link](http://nopweb20160822122620.azurewebsites.net/) is my website.

Thank you again for helping me solve these problem and also thanks for providing this great plugin.

**Comment by mobsoftware** [comment]
Thanks a lot. Can you verify two things:

1. No old MobSocial plugins still exist in the Plugins folder. This will cause the wrong routeprovider to be used.
2.  MobSocial Widget is enabled. This can also cause 404 statuses. 

Thanks,
Bruce

**Comment by 102306071** [comment]
Thanks Bruce.

The profile page works after I reinstall the plugin again and again.
Thanks a lot!
